/* ============================================================
   CODE ORIGIN.AI — Interactions
   ============================================================ */
(function () {
  'use strict';

  // ----- Sticky nav scroll state -----
  const nav = document.getElementById('nav');
  const onScroll = () => {
    if (window.scrollY > 12) nav.classList.add('scrolled');
    else nav.classList.remove('scrolled');
  };
  document.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  // ----- Mobile nav toggle -----
  const toggle = document.getElementById('navToggle');
  toggle?.addEventListener('click', () => {
    const open = nav.classList.toggle('open');
    toggle.setAttribute('aria-expanded', String(open));
  });
  document.querySelectorAll('.nav-links a').forEach(a => {
    a.addEventListener('click', () => nav.classList.remove('open'));
  });

  // ----- Product tabs -----
  const tabBtns = document.querySelectorAll('.tab-btn');
  const tabPanels = document.querySelectorAll('.tab-panel');
  tabBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.dataset.tab;
      tabBtns.forEach(b => b.classList.toggle('active', b === btn));
      tabPanels.forEach(p => p.classList.toggle('active', p.dataset.panel === target));
    });
  });

  // ----- Reveal on scroll -----
  if ('IntersectionObserver' in window) {
    const io = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.classList.add('in');
          io.unobserve(entry.target);
        }
      });
    }, { threshold: 0.12 });
    document.querySelectorAll('[data-reveal]').forEach(el => io.observe(el));
  } else {
    document.querySelectorAll('[data-reveal]').forEach(el => el.classList.add('in'));
  }

  // ----- Syntax highlighter (very small, custom) -----
  function highlight(code) {
    // Order matters: comments → strings → keywords → numbers
    const KEYWORDS = ['import','from','export','const','let','var','function','return','if','else','for','while','class','extends','new','await','async','of','in','typeof','interface','type','as','default'];
    let out = code
      .replace(/&/g,'&amp;')
      .replace(/</g,'&lt;')
      .replace(/>/g,'&gt;');
    out = out.replace(/(\/\/[^\n]*)/g, '<span class="tk-com">$1</span>');
    out = out.replace(/(['"`])(.*?)\1/g, '<span class="tk-str">$1$2$1</span>');
    const kwRe = new RegExp('\\b(' + KEYWORDS.join('|') + ')\\b', 'g');
    out = out.replace(kwRe, '<span class="tk-key">$1</span>');
    out = out.replace(/\b(\d+\.?\d*)\b/g, '<span class="tk-num">$1</span>');
    out = out.replace(/([A-Za-z_$][A-Za-z0-9_$]*)\s*\(/g, '<span class="tk-fn">$1</span>(');
    return out;
  }

  // ----- Typewriter effect -----
  function typewriter(target, text, speed = 14) {
    const el = document.getElementById(target);
    if (!el) return Promise.resolve();
    el.innerHTML = '';
    let i = 0;
    return new Promise(resolve => {
      const tick = () => {
        if (i >= text.length) { resolve(); return; }
        // Type chunks for speed (every ~3 chars)
        const chunk = text.slice(0, i + 1);
        el.innerHTML = highlight(chunk);
        i++;
        setTimeout(tick, speed + Math.random() * 12);
      };
      tick();
    });
  }

  const HERO_CODE = `// Origin Agent · planning new feature
import { agent } from '@codeorigin/sdk';

const result = await agent.run({
  goal: 'Add Stripe checkout to /pricing',
  repo: 'acme/web',
  tools: ['fs', 'shell', 'browser']
});

// → 6 files written, 14 tests passing
// → PR #482 opened: "feat(billing): stripe checkout"
console.log(result.pullRequest);
`;

  const DEMO_CODE = `// ThemeToggle.tsx · generated by Origin
import { useEffect, useState } from 'react';
import { saveUserPref } from '@/lib/api';

export function ThemeToggle({ userId }) {
  const [theme, setTheme] = useState('light');

  useEffect(() => {
    const saved = localStorage.getItem('theme');
    if (saved) setTheme(saved);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const toggle = async () => {
    const next = theme === 'light' ? 'dark' : 'light';
    setTheme(next);
    localStorage.setItem('theme', next);
    await saveUserPref(userId, { theme: next });
  };

  return (
    <button onClick={toggle} aria-label="Toggle theme">
      {theme === 'light' ? '🌙' : '☀️'}
    </button>
  );
}
`;

  // Loop the hero typewriter; trigger demo on visibility
  async function runHeroLoop() {
    while (true) {
      await typewriter('heroCode', HERO_CODE, 12);
      await new Promise(r => setTimeout(r, 3500));
    }
  }
  runHeroLoop();

  // Demo: type once when scrolled into view
  const demoEl = document.getElementById('demoCode');
  if (demoEl && 'IntersectionObserver' in window) {
    const demoIO = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          typewriter('demoCode', DEMO_CODE, 8);
          demoIO.disconnect();
        }
      });
    }, { threshold: 0.4 });
    demoIO.observe(demoEl);
  }

  // ----- Toast -----
  const toast = document.getElementById('toast');
  let toastTimer;
  function showToast(msg, type = 'success') {
    if (!toast) return;
    toast.textContent = msg;
    toast.className = 'toast show ' + type;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => toast.classList.remove('show'), 3500);
  }

  // ----- CTA subscribe (mock) -----
  window.codeOrigin = {
    subscribe(form) {
      const email = form.querySelector('input[type="email"]').value.trim();
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        showToast('Please enter a valid email.', 'error');
        return;
      }
      form.querySelector('button').textContent = 'Sending…';
      setTimeout(() => {
        showToast(`Welcome aboard, ${email.split('@')[0]}! Check your inbox.`, 'success');
        form.reset();
        form.querySelector('button').innerHTML = 'Start free →';
      }, 700);
    }
  };

  // ----- Smooth scroll for in-page links -----
  document.querySelectorAll('a[href^="#"]').forEach(a => {
    a.addEventListener('click', (e) => {
      const id = a.getAttribute('href');
      if (id.length > 1) {
        const target = document.querySelector(id);
        if (target) {
          e.preventDefault();
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      }
    });
  });

})();
